Listen 443 https

<VirtualHost _default_:443>
    DocumentRoot "/var/www/html"
    ServerName www.example.com:443
    
    SSLEngine on
    
    SSLCertificateFile /etc/pki/tls/certs/server.crt
    SSLCertificateKeyFile /etc/pki/tls/private/server.key
    
    <Directory "/var/www/html">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>